### ISSUE TITLE
Examples on glslb.in won't load

### ISSUE THREAD

**Issue by jarble** [glslify/glslify#128]
I tried to load some of the examples on http://glslb.in/, but none of the examples will load except for the first one (Simplex Noise). Are the required modules missing for these examples?

**Comment by ericmorand** [comment]
After a bit of investigation, I assume this is coming from the POST Ajax request to http://glslb.in/-/shader returning the following HTTP 500 error:

```
Missing package version (glsl-camera-ray)
Error: Missing package version (glsl-camera-ray)
    at getFile (/app/node_modules/npmdl/index.js:24:28)
    at gotVersion (/app/node_modules/glslify-resolve-remote/index.js:76:7)
    at Request._callback (/app/node_modules/glslify-resolve-remote/index.js:69:9)
    at Request.self.callback (/app/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:962:12)
```

Which explains the `Unexpected token M in JSON at position 0` in the console
